---
# tasks file for deploy-py-app
- name: Creating service folder "{{service_path}}"
  file: path="{{service_path}}" state=directory

- name: Copying docker-compose
  template:
    src: "{{docker_compose_src}}"
    dest: "{{service_path}}/docker-compose.yml"
  notify: restart

- name: Copying specified environment
  template:
    src: "{{service_env}}"
    dest: "{{service_path}}/.env"
  when: service_env != ""
  notify: restart

- name: Looking for host specific environment
  stat: 
    path: "{{host_specific_env}}"
  register: host_specific_file
  when: host_specific_env != ""

- name: Copying host specific environment
  template:
    src: "{{host_specific_env}}"
    dest: "{{service_path}}/.env"
  when: host_specific_file.stat.exists
  notify: restart

- name: Restarting service
  block:
    - name: Starting service
      service: name=docker-compose@{{service_name}} state=started enabled=yes

    - name: Waiting for service ports to come
      wait_for: host={{service_host}} port={{item.key}} timeout=100
      loop: "{{ service_ports | dict2items }}"

  rescue:
    - name: Collecting information
      command: systemctl status docker-compose@{{service_name}}
      register: result
    
    - name: Result
      debug: msg={{result.stdout}}
